#!/usr/bin/env python3
"""Generate pass-1b.tsv: bonsplit `TabID`/`Tab` names become bonsplitTab* so that
`tab`, `tabs`, `tabId` are free for the c11 tab (pass 2).

Run on the tree as it is after pass 1.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
# Files where tab/tabs/tabId are bonsplit leaf-tab names (see pass 1 LEAF_FILES).
LEAF = ["Sources/Workspace.swift", "Sources/WorkspaceContentView.swift", "Sources/TabSheetDetail.swift",
        "Sources/SocketHandlers/MiscHandlers.swift", "Sources/SocketHandlers/DebugHandlers.swift",
        "Sources/BrowserWindowPortal.swift", "Sources/WorkspacePlanCapture.swift",
        "Sources/WorkspaceLayoutExecutor.swift", "c11Tests/WorkspaceUnitTests.swift"]
GLOBAL = {  # c11 helpers that map between c11 ids and bonsplit TabIDs
    "panelIdFromSurfaceId": "tabIdFromBonsplitTabId",
    "surfaceIdFromPanelId": "bonsplitTabIdFromTabId",
    "surfaceIdToPanelId": "bonsplitTabIdToTabId",
}
LEAF_NAMES = {"tab": "bonsplitTab", "tabs": "bonsplitTabs", "tabId": "bonsplitTabId", "tabIds": "bonsplitTabIds",
              "selectedTabId": "selectedBonsplitTabId"}

# Members of bonsplit's ExternalPaneNode keep their vendor names.
FIXALL = [
    ("Sources/WorkspacePlanCapture.swift", "pane.bonsplitTabs", "pane.tabs"),
    ("Sources/WorkspacePlanCapture.swift", "pane.selectedBonsplitTabId", "pane.selectedTabId"),
    ("Sources/Workspace.swift", "guard let data = try? JSONEncoder().encode(surfaceId),\n              let decoded = try? JSONDecoder().decode(EncodedSurfaceID.self", "guard let data = try? JSONEncoder().encode(bonsplitTabId),\n              let decoded = try? JSONDecoder().decode(EncodedSurfaceID.self"),
    ("Sources/BrowserWindowPortal.swift", "transfer.tabId", "transfer.bonsplitTabId"),
    ("c11Tests/BrowserPanelTests.swift", "transfer?.tabId", "transfer?.bonsplitTabId"),
    ("Sources/Workspace.swift", "bonsplitTabId: request.tabId,", "bonsplitTabId: request.bonsplitTabId,"),  # PendingTabSelectionRequest
    ("c11Tests/BrowserPanelTests.swift", ".move(\n                tabId: bonsplitTabId,", ".move(\n                bonsplitTabId: bonsplitTabId,"),
    ("Sources/SocketHandlers/DebugHandlers.swift", "setLinkedHover(bonsplitTabId:", "setLinkedHover(tabId:"),
]

def main():
    out = ["# Pass 1b: bonsplit TabID names. Generated by gen-pass1b.py.",
           "# Columns: old<TAB>new<TAB>globs<TAB>fallback<TAB>flags"]
    for old, new in GLOBAL.items():
        out.append(f"{old}\t{new}\t")
    leaf = ",".join(LEAF)
    for old, new in LEAF_NAMES.items():
        out.append(f"{old}\t{new}\t{leaf}\t\tnoimplicit,nomember")
    # surfaceId typed TabID in Workspace.swift: only members that declare or derive a TabID.
    out.append("surfaceId\tbonsplitTabId\tSources/Workspace.swift\t\tnolabel")
    out.append("@keep\tSources/Workspace.swift\t\\A(?![\\s\\S]*(surfaceId: TabID|surfaceIdToPanelId|surfaceIdFromPanelId\\())\tsurfaceId")
    out.append("@callee\tmoveBonsplitTab\tkeep")  # declared outside the leaf files; its label stays tabId
    out.append("@callee\tBrowserPaneDragTransfer\trename")
    out.append("@callee\tpreloadTerminalPanelForDebugStress\trename")
    out.append("@callee\tmarkExplicitClose\trename")  # label follows its renamed declaration
    for rel, old, new in FIXALL:
        out.append(f"@fixall\t{rel}\t{old.replace(chr(10), '\\n')}\t{new.replace(chr(10), '\\n')}")
    with open(os.path.join(HERE, "pass-1b.tsv"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("pass-1b.tsv written")

if __name__ == "__main__":
    main()
