#!/usr/bin/env python3
"""Generate a segment-substitution pass table: pass-2a (Surface->Tab), pass-2b (Panel->Tab),
pass-3 (Pane->Area).

  gen-seg.py 2a|2b|3        run on the tree as it is after the previous pass

Every identifier whose camel-case segments contain the old word is renamed segment-wise
(`surfaceIdFromX` -> `tabIdFromX`), except the KEEP set (ghostty / bonsplit / IOSurface names)
and the curated EXPLICIT renames. New names that collide with an existing identifier are
reported so they can be resolved by hand. Test names (`test*`, `*Tests`) are left for a later pass.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import idents

HERE = os.path.dirname(os.path.abspath(__file__))

PASSES = {
    "2a": {
        "words": {"surface": "tab", "surfaces": "tabs"},
        # ghostty / IOSurface / bonsplit-facing surface names are not c11 tabs
        "keep": r"(?i)ghostty|iosurface|surfaceview|scrollprobe|TerminalSurface|terminalSurface|^surface_|_surface",
        "explicit": {
            "newTerminalSurface": "newTerminalTab",
            "newTerminalSurfaceInFocusedPane": "newTerminalTabInFocusedPane",
        },
        "file_exclude": ["!Sources/GhosttyTerminalView.swift", "!Sources/TerminalWindowPortal.swift",
                         "!c11Tests/TerminalAndGhosttyTests.swift"],
        "generic": {"surface", "surfaces"},  # bare tokens that need the file exclusions
    },
    "2b": {
        "words": {"panel": "tab", "panels": "tabs"},
        "keep": r"(?i)^$",
        "explicit": {
            "Panel": "TabContent", "PanelType": "TabContentType",
            "TerminalPanel": "TerminalTab", "BrowserPanel": "BrowserTab", "MarkdownPanel": "MarkdownTab",
        },
        "file_exclude": [],
        "generic": set(),
    },
    "3": {
        "words": {"pane": "area", "panes": "areas"},
        # bonsplit API (receiver/label names kept; found by compile errors) and c11 geometry words
        "keep": r"^(inPane|toPane|fromPane|focusedPaneId|allPaneIds|zoomedPaneId|railOpenPaneIds|"
                r"openTabSheetPaneIds|splitPane|closePane|focusPane|adjacentPane|togglePaneZoom|clearPaneZoom|"
                r"findPane|canClosePane|requestClosePane|splitPaneWithTab|allPaneBounds|allPanes|PaneID|"
                r"PaneGeometry|PaneState|ExternalPaneNode|ExternalPane\w*|didSplitPane|shouldSplitPane|"
                r"shouldClosePane|didFocusPane|onPaneClosed|allowCloseLastPane|allowCrossPaneTabMove|"
                r"autoCloseEmptyPanes|emptyPaneBuilder|paneOverlayBuilder|PaneBounds|paneBounds|focusedPane|"
                r"computePaneBounds|isFocusedPane|currentPaneId|newPaneId|newPaneIndex)$",
        "explicit": {},
        "file_exclude": [],
        "generic": set(),
    },
}
SKIP = re.compile(r"^test|Tests?$|UITests$|.+_")


def seg_replace(ident, words):
    parts = re.findall(r"[A-Z]+(?![a-z])|[A-Z]?[a-z0-9]+|[^A-Za-z0-9]+", ident)
    out, changed = [], False
    for i, p in enumerate(parts):
        low = p.lower()
        if low in words:
            new = words[low]
            if p[0].isupper():
                new = new[0].upper() + new[1:]
            out.append(new)
            changed = True
        else:
            out.append(p)
    return "".join(out) if changed else None


def main():
    which = sys.argv[1]
    cfg = PASSES[which]
    universe = idents.collect(".")
    keep = re.compile(cfg["keep"])
    rows, newnames = {}, {}
    for ident in sorted(universe):
        if SKIP.search(ident) or keep.search(ident):
            continue
        new = cfg["explicit"].get(ident) or seg_replace(ident, cfg["words"])
        if not new or new == ident:
            continue
        rows[ident] = new
    for ident, new in cfg["explicit"].items():
        if ident in universe:
            rows[ident] = new
    out = [f"# Pass {which}: segment renames. Generated by gen-seg.py; review before applying.",
           "# Columns: old<TAB>new<TAB>globs<TAB>fallback<TAB>flags"]
    dupes = {}
    for old, new in rows.items():
        dupes.setdefault(new, []).append(old)
    clashes = sorted(n for n in dupes if n in universe and n not in rows)
    for old in sorted(rows):
        globs = ",".join(cfg["file_exclude"]) if old in cfg["generic"] else ""
        out.append("\t".join([old, rows[old], globs]))
    path = os.path.join(HERE, f"pass-{which}.tsv")
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    multi = {n: o for n, o in dupes.items() if len(o) > 1}
    print(f"{len(rows)} entries -> {path}")
    print(f"{len(multi)} new names reached from several old names (expected for *Id merges)")
    for n in clashes:
        print(f"CLASH new name already exists: {n} (from {dupes[n]})")


if __name__ == "__main__":
    main()
