#!/usr/bin/env python3
"""Generate pass-1b.tsv: bonsplit `TabID`/`Tab` names become bonsplitTab* so that
`tab`, `tabs`, `tabId` are free for the c11 tab (pass 2).

Run on the tree as it is after pass 1.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
# Files where tab/tabs/tabId are bonsplit leaf-tab names (see pass 1 LEAF_FILES).
LEAF = ["Sources/Workspace.swift", "Sources/WorkspaceContentView.swift", "Sources/TabSheetDetail.swift",
        "Sources/SocketHandlers/MiscHandlers.swift", "Sources/SocketHandlers/DebugHandlers.swift",
        "Sources/BrowserWindowPortal.swift", "Sources/WorkspacePlanCapture.swift",
        "Sources/WorkspaceLayoutExecutor.swift", "c11Tests/WorkspaceUnitTests.swift"]
GLOBAL = {  # c11 helpers that map between c11 ids and bonsplit TabIDs
    "panelIdFromSurfaceId": "tabIdFromBonsplitTabId",
    "surfaceIdFromPanelId": "bonsplitTabIdFromTabId",
    "surfaceIdToPanelId": "bonsplitTabIdToTabId",
}
LEAF_NAMES = {"tab": "bonsplitTab", "tabs": "bonsplitTabs", "tabId": "bonsplitTabId", "tabIds": "bonsplitTabIds",
              "selectedTabId": "selectedBonsplitTabId"}

def main():
    out = ["# Pass 1b: bonsplit TabID names. Generated by gen-pass1b.py.",
           "# Columns: old<TAB>new<TAB>globs<TAB>fallback<TAB>flags"]
    for old, new in GLOBAL.items():
        out.append(f"{old}\t{new}\t")
    leaf = ",".join(LEAF)
    for old, new in LEAF_NAMES.items():
        out.append(f"{old}\t{new}\t{leaf}\t\tnoimplicit")
    # surfaceId typed TabID in Workspace.swift: only members that declare or derive a TabID.
    out.append("surfaceId\tbonsplitTabId\tSources/Workspace.swift")
    out.append("@keep\tSources/Workspace.swift\t\\A(?![\\s\\S]*(surfaceId: TabID|surfaceIdToPanelId|surfaceIdFromPanelId\\())\tsurfaceId")
    with open(os.path.join(HERE, "pass-1b.tsv"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("pass-1b.tsv written")

if __name__ == "__main__":
    main()
