#!/usr/bin/env bash
# run-r8.sh a|b|c [--commit] : C11-337 R8, internal Swift Tab -> Panel, one pass per call, on the tree as it stands.
#
#   a  restore the 2a/2b products to Panel (`Sources/Tabs` -> `Sources/Panels`)    gen-evidence.py r8a
#   b  names born Tab since, plus pass-r8b.hand.tsv (curated rows)                 gen-evidence.py r8b
#   c  test classes, functions and files; test lists; docs                         gen-p6.py r8c
#
# Each pass regenerates its table from the tree (never reuse an old run), applies it with its evidence log, applies
# pass-r8<x>.manual.patch if present, then runs every gate. --commit commits the pass when all gates report zero.
# Run a, b, c in order on a clean tree; `a` drops tables and logs left by an earlier run.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
x="$1"; p="r8$x"; d=scripts/vocab-rename
[[ "$x" =~ ^[abc]$ ]] || { echo "usage: run-r8.sh a|b|c [--commit]" >&2; exit 2; }
if [[ -n "$(git status --porcelain -- Sources CLI c11Tests c11UITests GhosttyTabs.xcodeproj)" ]]; then
  echo "run-r8: code paths are dirty; commit or reset first" >&2; exit 2
fi
base=$(git rev-parse HEAD)
if [[ "$x" == a ]]; then rm -f "$d"/pass-r8a.tsv "$d"/pass-r8b.tsv "$d"/pass-r8c.tsv "$d"/evidence-r8?.tsv; fi

case "$x" in
  a|b) python3 "$d/gen-evidence.py" "$p" ;;
  c)   python3 "$d/gen-p6.py" r8c ;;
esac
python3 "$d/rename.py" apply "$d/pass-$p.tsv" --evidence-log "$d/evidence-$p.tsv" | tee "/tmp/c11-vocab-pass-$p.log" | tail -4
if grep -q "FIXUP STALE" "/tmp/c11-vocab-pass-$p.log"; then echo "run-r8: stale @fix rows" >&2; exit 1; fi
if [[ -s "$d/pass-$p.manual.patch" ]]; then git apply --whitespace=nowarn "$d/pass-$p.manual.patch"; fi
python3 "$d/sync-test-lists.py" "$d/pass-$p.tsv"
if [[ "$x" == c ]]; then python3 "$d/sync-docs.py" r8a r8b r8c; fi

echo "---- gates ($p)"
fail=0
python3 "$d/rename.py" check-evidence "$d/evidence-$p.tsv" "$base" WORKTREE "$d/pass-$p.tsv" | tail -1 || fail=1
python3 "$d/rename.py" check-rows "$d/pass-$p.tsv" "$base" "$d/evidence-$p.tsv" | tail -12 || fail=1
python3 "$d/rename.py" check-domains | tail -1 || fail=1
python3 "$d/rename.py" check-literals | tail -1 || fail=1
tests=$(python3 "$d/test_rename.py" 2>&1) || true
if grep -q '^OK' <<<"$tests"; then grep '^Ran ' <<<"$tests"; else echo "test_rename.py failed"; fail=1; fi
if [[ "$fail" != 0 ]]; then echo "run-r8: gates not at zero for $p" >&2; exit 1; fi
echo "run-r8: $p gates at zero"
if [[ "${2:-}" == --commit ]]; then
  git add -A Sources CLI c11Tests c11UITests GhosttyTabs.xcodeproj "$d" .github scripts CLAUDE.md docs
  case "$x" in
    a) msg="C11-337 R8 pass A: restore the panel names (Sources/Tabs -> Sources/Panels, 2a/2b products -> Panel)" ;;
    b) msg="C11-337 R8 pass B: names born Tab since 10-01 follow panel (Journal/Feed, panel sheet, Panel Layout, rail tip, #596-#598)" ;;
    c) msg="C11-337 R8 pass C: test classes, functions, files and test lists follow panel" ;;
  esac
  git commit -q -m "$msg" -m "Generated by scripts/vocab-rename/run-r8.sh $x on $(git rev-parse --short "$base")." \
    -m "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>"
  git log --oneline -1
fi
