import Foundation

// MARK: - Model catalog store (C11-203 Part D)
//
// Three tiers, best-available wins, nothing on a UI path:
//
//   1. **Live enumeration** — the harness CLIs, run off-main under a per-command
//      timeout by `refresh(completion:)`. Never automatic on a launch path; the
//      caller decides when (opening the editor is the natural trigger).
//   2. **On-disk cache** — `model-catalog.tsv` at the c11 state root, written
//      after every successful refresh, loaded asynchronously at startup.
//   3. **Compiled snapshot** — `ModelCatalogSnapshot`, generated by
//      `scripts/generate-model-catalog-snapshot.sh` and committed. Parsed
//      synchronously in `init` so the very first read already has a full
//      catalog: it is a string split, no I/O and no subprocess.
//
// Degradation is per-harness and additive: a refresh that cannot reach `grok`
// keeps the grok rows it already had. The catalog can improve on a bad day; it
// cannot empty out.

final class ModelCatalogStore: ModelCatalogProviding, @unchecked Sendable {

    /// Cache filename at the c11 state root.
    static let fileName = "model-catalog.tsv"

    /// Process-wide catalog.
    static let shared = ModelCatalogStore()

    /// Build `shared` off the main thread. First access parses the compiled
    /// snapshot and builds the index — around 13 ms in Release and 30 ms in
    /// Debug for the ~1,400-row catalog. That is cheap, but it is cheaper still
    /// on a background queue: call this once at startup so the first picker
    /// open finds the catalog already built.
    static func warm() {
        DispatchQueue.global(qos: .utility).async { _ = ModelCatalogStore.shared }
    }

    private let cacheURL: URL?
    private let enumerator: ModelCatalogEnumerator?
    private let queue = DispatchQueue(label: "com.stage11.c11.model-catalog", qos: .utility)
    private let lock = NSLock()

    private var _records: [RawCatalogRecord]
    private var _index: ModelCatalogIndex
    private var refreshInFlight = false
    private var pendingCompletions: [() -> Void] = []

    // MARK: Init

    /// - Parameters:
    ///   - directory: state root for the cache. `nil` resolves the c11 state
    ///     root the same way `AgentConfigLibraryStore` does. Pass an explicit
    ///     temporary directory in tests.
    ///   - runner: subprocess seam. `nil` disables live enumeration entirely
    ///     (cache + snapshot only), which is what tests want by default.
    ///   - snapshot: records compiled into the binary.
    ///   - snapshotGeneratedAt: provenance for `snapshot`, compared against the
    ///     cache's own stamp so an app update carrying a fresher snapshot wins
    ///     over a stale cache.
    ///   - loadCacheAsynchronously: `false` loads the cache inline, so a test
    ///     can assert on it without waiting.
    init(
        directory: URL? = nil,
        runner: ModelCatalogCommandRunning? = ProcessModelCatalogCommandRunner(),
        snapshot: [RawCatalogRecord] = ModelCatalogSnapshot.records,
        snapshotGeneratedAt: Date? = ModelCatalogSnapshot.generatedAt,
        loadCacheAsynchronously: Bool = true
    ) {
        let root = directory ?? ModelCatalogStore.defaultDirectory()
        self.cacheURL = root?.appendingPathComponent(ModelCatalogStore.fileName, isDirectory: false)
        self.enumerator = runner.map { ModelCatalogEnumerator(runner: $0) }
        self._records = snapshot
        self._index = ModelCatalogBuilder.build(
            records: snapshot,
            source: .snapshot,
            generatedAt: snapshotGeneratedAt
        )

        if loadCacheAsynchronously {
            queue.async { [weak self] in self?.adoptCacheIfBetter() }
        } else {
            adoptCacheIfBetter()
        }
    }

    /// The c11 state root, resolved exactly as the config library resolves it so
    /// the cache lands beside `agent-configs.json`.
    static func defaultDirectory(fileManager: FileManager = .default) -> URL? {
        if let url = try? EventLogLayout.defaultStateURL(fileManager: fileManager) { return url }
        guard let base = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
        else { return nil }
        return base.appendingPathComponent(EventLogLayout.stateDirectoryName, isDirectory: true)
    }

    // MARK: Reads

    /// The live index. Cheap; safe from any thread.
    var index: ModelCatalogIndex {
        lock.lock(); defer { lock.unlock() }
        return _index
    }

    /// The raw records behind the current index (cache/snapshot provenance
    /// included). Exposed for diagnostics and for the snapshot generator.
    var records: [RawCatalogRecord] {
        lock.lock(); defer { lock.unlock() }
        return _records
    }

    func providers() -> [String] { index.providers }

    func models(forProvider provider: String) -> [CatalogModel] {
        index.models(forProvider: provider)
    }

    func harnesses(forModel model: CatalogModel) -> [String] {
        index.harnesses(forModel: model)
    }

    func allModels() -> [CatalogModel] { index.allModels }

    func model(provider: String, id: String) -> CatalogModel? {
        index.model(provider: provider, id: id)
    }

    /// The exact value to hand `harness`'s model flag. Falls back to
    /// `model.id`, which is correct for every harness that takes a bare id
    /// (codex, claude-code, kimi, grok, pi) and wrong only for a harness that
    /// never published the model — in which case the pair should not have been
    /// offered.
    func modelFlagValue(for model: CatalogModel, harness: String) -> String {
        index.modelFlagValue(for: model, harness: harness) ?? model.id
    }

    /// What `harness` publishes about this model's effort levels.
    /// `.unspecified` → use the harness manifest's own values; `.none` → hide
    /// the effort control; `.values` → intersect with the manifest's values.
    func effortSupport(for model: CatalogModel, harness: String) -> ModelEffortSupport {
        index.effortSupport(for: model, harness: harness)
    }

    /// Substring search over id and display name, prefix matches first. The
    /// OpenRouter tier alone is several hundred models, so the picker filters
    /// rather than scrolling.
    func search(_ query: String, provider: String? = nil, limit: Int = 50) -> [CatalogModel] {
        let needle = query.trimmingCharacters(in: .whitespaces).lowercased()
        let pool = provider.map { models(forProvider: $0) } ?? allModels()
        guard !needle.isEmpty else { return Array(pool.prefix(limit)) }
        var prefix: [CatalogModel] = []
        var contains: [CatalogModel] = []
        for model in pool {
            let id = model.id.lowercased()
            let name = model.displayName.lowercased()
            if id.hasPrefix(needle) || name.hasPrefix(needle) {
                prefix.append(model)
            } else if id.contains(needle) || name.contains(needle) {
                contains.append(model)
            }
        }
        return Array((prefix + contains).prefix(limit))
    }

    // MARK: Refresh

    /// Re-enumerate every harness CLI off-main and swap the index in.
    /// `completion` runs on the main queue. Concurrent calls coalesce onto the
    /// in-flight pass rather than spawning a second wave of subprocesses.
    func refresh(completion: @escaping () -> Void) {
        guard enumerator != nil else {
            DispatchQueue.main.async(execute: completion)
            return
        }
        lock.lock()
        if refreshInFlight {
            pendingCompletions.append(completion)
            lock.unlock()
            return
        }
        refreshInFlight = true
        pendingCompletions.append(completion)
        lock.unlock()

        queue.async { [weak self] in
            guard let self else { return }
            self.performRefresh()
            self.lock.lock()
            let waiting = self.pendingCompletions
            self.pendingCompletions = []
            self.refreshInFlight = false
            self.lock.unlock()
            DispatchQueue.main.async { waiting.forEach { $0() } }
        }
    }

    /// Refresh only when the current catalog is older than `maxAge` (or has no
    /// provenance date at all). Cheap to call on every editor open.
    func refreshIfStale(maxAge: TimeInterval = 6 * 3600, completion: @escaping () -> Void = {}) {
        let stamp = index.generatedAt
        let stale = stamp.map { Date().timeIntervalSince($0) > maxAge } ?? true
        guard stale else {
            DispatchQueue.main.async(execute: completion)
            return
        }
        refresh(completion: completion)
    }

    /// Blocking refresh, for the snapshot generator and tests with a stubbed
    /// runner. Never call this from the app.
    @discardableResult
    func refreshSynchronously() -> Bool {
        guard enumerator != nil else { return false }
        return queue.sync { performRefresh() }
    }

    @discardableResult
    private func performRefresh() -> Bool {
        guard let enumerator else { return false }
        let live = enumerator.enumerateAll()
        guard !live.isEmpty else { return false }

        lock.lock()
        let previous = _records
        lock.unlock()

        let merged = ModelCatalogEnumerator.merged(live: live, previous: previous)
        let now = Date()
        let built = ModelCatalogBuilder.build(records: merged, source: .live, generatedAt: now)
        guard !built.isEmpty else { return false }

        lock.lock()
        _records = merged
        _index = built
        lock.unlock()

        writeCache(records: merged, generatedAt: now)
        return true
    }

    // MARK: Cache

    /// Adopt the disk cache when it is newer than what we already hold. An app
    /// update can ship a snapshot newer than a stale cache; the newer
    /// provenance date wins either way.
    private func adoptCacheIfBetter() {
        guard let cacheURL, let text = try? String(contentsOf: cacheURL, encoding: .utf8) else { return }
        let records = ModelCatalogRecordCodec.decode(text)
        guard !records.isEmpty else { return }
        let stamp = Self.parseGeneratedAt(text)

        lock.lock()
        let currentStamp = _index.generatedAt
        lock.unlock()
        // Dated snapshot vs dated cache: newer wins. An undated cache never
        // displaces a dated snapshot; an undated snapshot always yields.
        if let currentStamp {
            guard let stamp, stamp > currentStamp else { return }
        }

        let built = ModelCatalogBuilder.build(records: records, source: .cache, generatedAt: stamp)
        guard !built.isEmpty else { return }
        lock.lock()
        _records = records
        _index = built
        lock.unlock()
    }

    private func writeCache(records: [RawCatalogRecord], generatedAt: Date) {
        guard let cacheURL else { return }
        let header = """
        # c11 model catalog cache (C11-203). Regenerated by ModelCatalogStore.refresh.
        # schema_version: 1
        # generated_at: \(ISO8601DateFormatter().string(from: generatedAt))

        """
        let body = ModelCatalogRecordCodec.encode(records)
        guard let data = (header + body + "\n").data(using: .utf8) else { return }
        try? FileManager.default.createDirectory(
            at: cacheURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try? data.write(to: cacheURL, options: .atomic)
    }

    static func parseGeneratedAt(_ text: String) -> Date? {
        for line in text.split(separator: "\n") {
            guard line.hasPrefix("#"), let range = line.range(of: "generated_at:") else { continue }
            let value = line[range.upperBound...].trimmingCharacters(in: .whitespaces)
            return ISO8601DateFormatter().date(from: value)
        }
        return nil
    }
}
